import { IconCameraHeart, IconChefHat, IconHeartHandshake } from "@tabler/icons-react"

export type Review = {
  name: string
  category: string
  area: string
  rating: number
  highlight: string
  budget: string
  vibe: string
  bestFor: string
  note: string
  insight: string
  image: string
}

export const sections = ["Home", "About", "Reviews", "Collab", "Contact"] as const

export type Section = (typeof sections)[number]

export const reviewsPerPage = 5

export const reviews: Review[] = [
  {
    name: "Kopi Klotok",
    category: "Javanese Comfort Food",
    area: "Pakem",
    rating: 4.8,
    highlight: "pisang goreng, sayur lodeh, and homey rice plates",
    budget: "Rp25k-60k",
    vibe: "rural, nostalgic, ramai tapi hangat",
    bestFor: "family breakfast and weekend food trip",
    note: "Rasa rumahan yang konsisten, ambience sawahnya kuat, dan cocok banget untuk konten Jogja yang feels authentic.",
    insight: "Strong for brands that want heritage, local warmth, and high save potential.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Tempo Gelato",
    category: "Gelato",
    area: "Prawirotaman",
    rating: 4.7,
    highlight: "pistachio gelato and seasonal fruit flavors",
    budget: "Rp30k-55k",
    vibe: "touristy, colorful, easy to recommend",
    bestFor: "after-lunch dessert and quick reels",
    note: "Flavor banyak, queue-nya iconic, dan visual gelato selalu aman untuk carousel yang playful.",
    insight: "Great for high-traffic dessert campaigns and quick visual hooks.",
    image: "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Mediterranea Restaurant",
    category: "Mediterranean",
    area: "Tirtodipuran",
    rating: 4.6,
    highlight: "pasta, steak, and warm bread basket",
    budget: "Rp80k-180k",
    vibe: "polished, intimate, dinner-friendly",
    bestFor: "date night and premium menu tasting",
    note: "Service rapi, menu luas, dan plating-nya punya feel upscale tanpa terasa kaku.",
    insight: "Good fit for restaurants targeting couples, expats, and premium casual diners.",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Epic Coffee",
    category: "Cafe",
    area: "Palagan",
    rating: 4.5,
    highlight: "brunch plates and iced coffee",
    budget: "Rp45k-120k",
    vibe: "industrial, spacious, work-friendly",
    bestFor: "remote work and brunch content",
    note: "Tempatnya lega, lighting oke, dan mudah dipakai untuk konten cafe productivity yang modern.",
    insight: "Useful for lifestyle brands that want cafe-working audience exposure.",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Chocolate Monggo",
    category: "Chocolate Shop",
    area: "Kotagede",
    rating: 4.4,
    highlight: "local chocolate tasting and souvenir boxes",
    budget: "Rp35k-150k",
    vibe: "sweet, local craft, giftable",
    bestFor: "souvenir hunting and product content",
    note: "Packaging cantik, rasa cokelat lokalnya kuat, dan cocok untuk konten oleh-oleh premium dari Jogja.",
    insight: "Strong product storytelling angle for gifting and local craft positioning.",
    image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Gudeg Yu Djum",
    category: "Gudeg",
    area: "Wijilan",
    rating: 4.6,
    highlight: "classic gudeg krecek and ayam kampung",
    budget: "Rp35k-85k",
    vibe: "legendary, local, no-frills",
    bestFor: "first-time Jogja food guide",
    note: "Manisnya khas Jogja, porsinya satisfying, dan wajib masuk list untuk audience luar kota.",
    insight: "Best for destination content and local culinary identity.",
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Roaster and Bear",
    category: "Cafe",
    area: "Gowongan",
    rating: 4.3,
    highlight: "coffee, pancakes, and cute bear-themed corners",
    budget: "Rp45k-130k",
    vibe: "cute, central, photo-friendly",
    bestFor: "casual meetups and cute cafe posts",
    note: "Lokasi strategis, menu aman untuk banyak selera, dan visual interiornya gampang dipakai untuk soft content.",
    insight: "Good for accessible creator meetups and everyday cafe campaigns.",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Sate Klathak Pak Pong",
    category: "Satay",
    area: "Imogiri",
    rating: 4.7,
    highlight: "sate klathak, gulai, and smoky skewers",
    budget: "Rp40k-95k",
    vibe: "rustic, busy, deeply local",
    bestFor: "night food trip and local legend content",
    note: "Smoky, sederhana, dan punya cerita kuat. Ini tipe tempat yang bikin audience pengin road trip malam.",
    insight: "High story value for local food trail and travel food content.",
    image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Milas Vegetarian",
    category: "Vegetarian",
    area: "Prawirotaman",
    rating: 4.5,
    highlight: "plant-based bowls and garden dining",
    budget: "Rp35k-90k",
    vibe: "green, mindful, slow afternoon",
    bestFor: "healthy lunch and vegan-friendly guides",
    note: "Rasanya clean tanpa hambar, suasananya adem, dan cocok untuk konten mindful eating di Jogja.",
    insight: "Good for wellness brands and conscious dining positioning.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Warung Bu Ageng",
    category: "Indonesian",
    area: "Tirtodipuran",
    rating: 4.4,
    highlight: "nasi campur, brongkos, and traditional sides",
    budget: "Rp35k-100k",
    vibe: "heritage, warm, family-friendly",
    bestFor: "traditional lunch and group dining",
    note: "Menu Indonesia-nya approachable, ambience rumah lama terasa, dan cocok untuk review yang informatif.",
    insight: "Solid for family dining and local heritage campaigns.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Hayati Specialty Coffee",
    category: "Coffee",
    area: "Demangan",
    rating: 4.6,
    highlight: "manual brew and pastry pairing",
    budget: "Rp35k-95k",
    vibe: "minimal, calm, coffee-serious",
    bestFor: "coffee tasting and slow content",
    note: "Kopinya clean, baristanya informatif, dan cocok untuk audience yang suka detail flavor notes.",
    insight: "Best for specialty coffee storytelling and education-led posts.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Nanamia Pizzeria",
    category: "Pizza",
    area: "Tirtodipuran",
    rating: 4.5,
    highlight: "wood-fired pizza and casual Italian plates",
    budget: "Rp65k-160k",
    vibe: "garden, casual, group-friendly",
    bestFor: "dinner with friends",
    note: "Pizza crust-nya enjoyable, tempatnya nyaman, dan cocok untuk konten sharing menu.",
    insight: "Good for social dining content and group package promotions.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Soto Kadipiro",
    category: "Soto",
    area: "Wirobrajan",
    rating: 4.4,
    highlight: "clear chicken soto and classic sides",
    budget: "Rp20k-55k",
    vibe: "classic, quick, comforting",
    bestFor: "breakfast and local food list",
    note: "Kuahnya ringan tapi gurih, service cepat, dan cocok untuk konten sarapan Jogja.",
    insight: "Strong evergreen content for affordable local recommendations.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "The House of Raminten",
    category: "Indonesian",
    area: "Kotabaru",
    rating: 4.3,
    highlight: "traditional menu and theatrical ambience",
    budget: "Rp25k-95k",
    vibe: "quirky, cultural, late-night friendly",
    bestFor: "unique Jogja experience",
    note: "Experience-nya kuat, menu banyak, dan cocok untuk audience yang cari tempat makan sekaligus cerita.",
    insight: "Useful for experience-led campaigns with strong local character.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "ViaVia Jogja",
    category: "Global Casual",
    area: "Prawirotaman",
    rating: 4.4,
    highlight: "global comfort plates and bakery treats",
    budget: "Rp45k-130k",
    vibe: "traveler-friendly, relaxed, artsy",
    bestFor: "brunch and travel audience",
    note: "Menu internasionalnya approachable, bakery enak, dan vibe-nya cocok untuk konten travel slow day.",
    insight: "Good for tourism, travel, and mixed local-international audience.",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Sate Ratu",
    category: "Satay",
    area: "Sleman",
    rating: 4.7,
    highlight: "sate merah and spicy grilled chicken skewers",
    budget: "Rp35k-85k",
    vibe: "bold, casual, flavor-forward",
    bestFor: "spicy food hunters",
    note: "Bumbunya nendang, konsepnya jelas, dan sangat mudah dibuat jadi konten reaction yang engaging.",
    insight: "Strong hook for bold flavor launches and spicy food campaigns.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Klinik Kopi",
    category: "Coffee Experience",
    area: "Sleman",
    rating: 4.6,
    highlight: "single-origin coffee storytelling",
    budget: "Rp30k-75k",
    vibe: "intimate, educational, slow",
    bestFor: "coffee lovers and story-first content",
    note: "Experience minum kopinya personal, cerita bijinya kuat, dan cocok untuk konten naratif.",
    insight: "Best for brands that value education, process, and origin stories.",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Jejamuran",
    category: "Mushroom Restaurant",
    area: "Sleman",
    rating: 4.5,
    highlight: "mushroom satay, soup, and crispy mushroom",
    budget: "Rp30k-90k",
    vibe: "family-friendly, unique, local favorite",
    bestFor: "group lunch and unique menu guide",
    note: "Konsep jamurnya beda, menu variatif, dan recommended untuk audience yang ingin tempat family-friendly.",
    insight: "Good for unique menu positioning and family dining campaigns.",
    image: "https://images.unsplash.com/photo-1504545102780-26774c1bb073?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Bakmi Jawa Mbah Gito",
    category: "Bakmi Jawa",
    area: "Kotagede",
    rating: 4.6,
    highlight: "bakmi godog and rustic wooden ambience",
    budget: "Rp30k-75k",
    vibe: "rustic, warm, deeply Jogja",
    bestFor: "dinner and local atmosphere content",
    note: "Bakmi-nya comforting, interiornya punya karakter, dan bagus untuk storytelling visual malam.",
    insight: "Strong for local dining campaigns that need atmosphere and heritage.",
    image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=85",
  },
  {
    name: "Il Tempo del Gelato",
    category: "Dessert",
    area: "Kaliurang",
    rating: 4.4,
    highlight: "creamy gelato and casual hangout setup",
    budget: "Rp25k-55k",
    vibe: "sweet, simple, student-friendly",
    bestFor: "dessert break and campus-area content",
    note: "Pilihan rasanya fun, harga masih friendly, dan cocok untuk list dessert Jogja yang accessible.",
    insight: "Good for student audience and affordable dessert campaigns.",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=900&q=85",
  },
]

export const profileStats = [
  { value: "20", label: "Jogja reviews" },
  { value: "5", label: "shown per page" },
  { value: "4.6/5", label: "avg rating" },
]

export const contentFormats = [
  "Jogja cafe review reels",
  "Menu tasting story set",
  "Soft-launch visit",
  "Photo carousel recap",
]

export const personalityNotes = [
  {
    icon: IconChefHat,
    title: "Honest taste notes",
    copy: "Bahasa ringan, tapi tetap jelas soal rasa, texture, price point, dan service.",
  },
  {
    icon: IconCameraHeart,
    title: "Pretty food visuals",
    copy: "Konten dibuat saveable, shareable, dan membantu tempat makan Jogja terlihat inviting.",
  },
  {
    icon: IconHeartHandshake,
    title: "Brand-friendly workflow",
    copy: "Scope collaboration transparan supaya ekspektasi brand dan creator align dari awal.",
  },
]
